### ISSUE TITLE
storePage

### ISSUE THREAD

**Issue by yujin9747** [shinel98/FoodHunter#18]
**Description**
- 크롬으로 작동 시 달라진 UI 개선
- 리뷰 취소 시 폼 초기화 
**Todo**
- [x] 리뷰 작성 모달 UI 수정
- [x] 리뷰 취소 시 폼 초기화
- [x] 중복 리뷰 작성 시 페이지 이동 X, 경고창 띄우기로 수정

**ETC**
-
