### ISSUE TITLE
가게 상세 페이지

### ISSUE THREAD

**Issue by yujin9747** [shinel98/FoodHunter#20]
**Description**
- store.jsp, visit.jsp
**Todo**
- [x] css, js 파일 분류
- [x] 내 위치 마커 표시
- [x] 실시간 거리 계산
- [x] 방문인증 정보 controller로 넘기고, store페이지로 돌아가며 "인증 완료" 알림창 띄우기

**ETC**
- 방문인증 버튼을 원래 카테고리 이미지로 했는데 그냥 버튼 디자인으로 바꿨습니다. -> 폼 제출해야 해서
