### ISSUE TITLE
가게, 방문인증 페이지

### ISSUE THREAD

**Issue by yujin9747** [shinel98/FoodHunter#31]
**Description**
- API 구현 완성, 3주차 월요일 전체 모임때 받은 피드백 반영 -> 3주차 수요일 저녁 팀 모임 전까지 목표
**Todo**
- [x] 중복리뷰, 방문인증 경고창을 모달로 바꾸기
- [x] 가게 제보 시, 요일 선택 UI 구현
- [x] 이름 자동 생성 API 구현 ->가게 제보 상세페이지, 마이페이지에 적용한 상태
- [x] 가게제보-메인페이지로 이동 : 제보완료 모달 구현

**ETC**
- CORS 문제 아직 더 해결해야 함. 크롬브라우저 확장자 설치해서 테스트는 돌려봤지만.. 확장자 없이도 데이터 받아올 수 있도록 수정 예정
- my page, report-detail 페이지에 랜덤 이름 생성 api 넣어놨으니 활용하면 됨. 
- 후에 닉네임 생성 페이지 완성되면 여기에도 넣기.
- 가게 이름 랜덤 생성은, api에서 받아온 관형사 + 카테고리 이름 명사 조합으로 만들었음.
