### ISSUE TITLE
관리자 페이지 DB 연결

### ISSUE THREAD

**Issue by yangsijun** [shinel98/FoodHunter#46]
**Description**
- Admin Page를 DB와 연결합니다.
**Todo**
- [x] category-mapper.xml 생성
- [x] mybatis-config.xml 수정
- [x] Category.java (DTO) 생성
- [x] CategoryDAO.java 생성
- [x] CategoryService 생성
- [x] CategoryServiceImpl 구현
- [x] admin.jsp에서 DB 데이터 사용하도록 수정
- [x] 카테고리 추가 요청 승인/거절 구현

**ETC**
- 기타사항 없습니다.
