### ISSUE TITLE
main페이지 backend 구현

### ISSUE THREAD

**Issue by shinel98** [shinel98/FoodHunter#49]
**Description**
- 메인 페이지 DB 연결 데이터 불러오기
**Todo**
- [x] 가게 이름, 태그 읽어와서 출력하기
- [x] 카테고리 읽어와서 출력하기
- [x] 거리 읽어와서 계산하여 출력하기
- [x] 좋아요 수 읽어와서 출력하기
- [x] 태그 필터링 기능 구현하기
- [ ] 현재 위치에서 재검색 기능 구현하기
- [ ] 내 위치로 이동 기능 구현하기

**ETC**
