### ISSUE TITLE
가게 상세 페이지 Front-End

### ISSUE THREAD

**Issue by yujin9747** [shinel98/FoodHunter#5]
**Description**
- 가게 상세 페이지, 방문인증페이지를 맡았습니다
**Todo**
- [x] 가게 상세 페이지 html, css 1차 완성 (store.jsp) by 1/1
- [x] 방문 인증 페이지 html, css 1차 완성 (visit.jsp) by 1/1
- [x] StoreController : store.jsp, visit.jsp 맵핑 

**ETC**
- 카테고리 이미지(ex. 붕어빵) webapp/resources/img 안에 임의로 넣어뒀습니다. -> 나린 학우님이 넣어주신 이미지로 쓸 예정
- 카테고리 이미지 "category-imgName.확장자" 포맷으로 통일하기로 했습니다. 
- css, javascript 코드 파일 분류 아직 안했습니다 -> 경로 못찾는 오류. 해결 후 분류하겠습니다. 
- 이슈 만들기 전에 push한 코드라 "yujin" 브랜치로 넣어놨습니다.
