### ISSUE TITLE
가게페이지

### ISSUE THREAD

**Issue by yujin9747** [shinel98/FoodHunter#51]
**Description**
- 1/17일 화요일 미팅 전까지 해야 할 일들
**Todo**
- [x] 가게 create
- [x] 메인페이지에서 가게 클릭하면 가게 페이지로 넘어가는 것 구현
- [ ] CORS 문제 해결
- [ ] 좋아요 누르는 부분 버그 해결
- [x] km로 가게페이지에 표시
- [x] m로 방문인증 페이지에 표시

**ETC**
- 가게 마커 생성할 때 지도 클릭하면 위도 받아오는 부분이 잘 안됩니다.
