### ISSUE TITLE
main 페이지 수정, 로그인 페이지 구현

### ISSUE THREAD

**Issue by shinel98** [shinel98/FoodHunter#54]
**Description**
- 
**Todo**
- [x] 모바일 뷰와 웹뷰 태그 클릭 시 색상 변하는 것 통일 
- [x] 태그 필터링 기능 완성
- [x] 카카오 로그인 기능 구현
- [x] interceptor 구현

**ETC**
