### ISSUE TITLE
가게 정보 jps뿌리기, 가게 create 등

### ISSUE THREAD

**Issue by yujin9747** [shinel98/FoodHunter#58]
**Description**
- 1/18일 수요일 배포 전까지 할 일 - 유진

**Todo**
- [x] store, review read 해온 것 jsp 페이지에 뿌리기
- [x] review 삭제
- [x] store create 에서 위도, 경도 저장하기
- [x] store create validation 구현
- [x] store create 요일 추가(콤마)하기
- [x] store create 카테고리 여러개 선택 처리하기
- [ ] 좋아요 버그 수정
- [ ] 닉네임 자동 생성 CORS 에러 수정
- [x] 닉네임 자동 생성 NullPointerException 수정

**ETC**
- 화이팅!
