### ISSUE TITLE
store create, 좋아요 등 잔 버그 수정

### ISSUE THREAD

**Issue by yujin9747** [shinel98/FoodHunter#72]
**Description**
- 1/18일 수요일 마지막 미팅 후 남은 과제 -> 19일 목요일 프로젝트 마감일

**Todo**
- [x] 좋아요 create 오류 수정
- [x] 이미 좋아요 한 가게의 하트 아이콘 채우기
- [x] 좋아요 delete 구현
- [ ] CORS 오류 수정
- [x] 가게 create 할 때 행정지역명 보여주기
- [x] 카카오 공유 위치보기 address에 행정지역 주소 넣기
- [x] 카테고리 추가 신청 완료 후, report/detail 페이지로 리디렉션 하기
- [x] 카카오 공유 카테고리 이미지 나오도록 수정 -> 일단 대표이미지 나오도록 수정함
- [x] 사진 있는 리뷰 -> 사진경로 설정
- [x] 사진 여러개인 리뷰 -> 스크롤로 여러개 볼 수 있도록 수정
- [ ] 배포 이후 카카오 서비스 domain 추가 및 테스트
- [x] 리뷰 delete 이후 리디렉션 오류 수정
- [x] 리뷰 create 오류 수정
- [x] 리뷰 삭제 아이콘 스타일 적용안되는거 수정하기
- [x] 좋아요 form으로 바꿔서 바뀐 스타일 수정하기

**ETC**
- 19일 오후 5시 배포
- 19일 오후 9시 최종 발표
- 리뷰 삭제 이후 리디렉션 오류는 수정했으나, 이전에 만들어둔 삭제 완료 모달은 안 뜨는 상태
